### ISSUE TITLE
Repositories are sorted alphabetically (2.30.0)

### ISSUE THREAD

**Issue by mbrodala** [localheinz/composer-normalize#1059]
#### Steps required to reproduce the problem

1. Have a `composer.json` with `repositories`
2. Have at least one `local` repository and another repository
3. Give `local` a name which alphabetically follows the other repository (e.g. `local` for `local` and `foo` for a custom VCS package)

So given a `composer.json` like this:

```json
{
    "repositories": {
        "local": {
            "type": "path",
            "url": "./packages/*/"
        },
        "foo": {
            "type": "vcs",
            "url": "..."
        }
    }
}
```

#### Expected Result

- the `repositories` order is left unchanged on normalization (example above: `local` stays before `foo`)

#### Actual Result

- the `repositories` are sorted alphabetically which must not happen (example above: `foo` is sorted before `local`)

See https://getcomposer.org/doc/04-schema.md#repositories

> **Note**: Order is significant here. When looking for a package, Composer will look from the first to the last repository, and pick the first match.

**Comment by localheinz** [comment]
@mbrodala 

Interesting, I did not know that `repositories` could be an `array` or an `object`. 

Thank you for opening an issue!

**Comment by localheinz** [comment]
@mbrodala 

Released as https://github.com/ergebnis/composer-normalize/releases/tag/2.30.1!

**Comment by mbrodala** [comment]
Thanks a lot for the fix!

**Comment by localheinz** [comment]
You are welcome, @mbrodala!
