### ISSUE TITLE
Bug: Reorders dependency versions

### ISSUE THREAD

**Issue by oliverklee** [localheinz/composer-normalize#1061]
#### Steps required to reproduce the problem

1. Start with a `composer.json` with which composer-normalize is happy.
2. Add this as a requirement in your `composer.json`: `"sjbr/static-info-tables": "^6.9.6 || ^11.5.3"`
3. Run composer-normalize.

#### Expected Result

No changes.

#### Actual Result

```
 ./composer.json is not normalized.

---------- begin diff ----------
--- original
+++ normalized
@@ -39,7 +39,7 @@
 		"phpunit/phpunit": "^8.5.33",
 		"saschaegerer/phpstan-typo3": "^1.8.2",
 		"seld/jsonlint": "^1.9.0",
-		"sjbr/static-info-tables": "^6.9.6 || ^11.5.3",
+		"sjbr/static-info-tables": "^11.5.3 || ^6.9.6",
 		"squizlabs/php_codesniffer": "^3.7.2",
 		"symfony/routing": "^5.4.11 || ^6.1.3",
 		"symfony/yaml": "^4.4.37 || ^5.3.14 || ^6.0.2",

----------- end diff -----------
```

#### Additional information

This is with C-N 2.30.1 on PHP 8.1.

As far as I can tell, this is a regression starting with 2.30.0 or 2.30.1.

**Comment by localheinz** [comment]
Thank you for reporting, @oliverklee!

**Comment by localheinz** [comment]
Fixed with #1062.

**Comment by localheinz** [comment]
Released as https://github.com/ergebnis/composer-normalize/releases/tag/2.30.2.

**Comment by oliverklee** [comment]
Wow, that was fast! Thank you, @localheinz! :heart:

**Comment by localheinz** [comment]
You are welcome, @oliverklee!
