### ISSUE TITLE
Provide a security policy for this library

### ISSUE THREAD

**Issue by TravisCarden** [localheinz/composer-normalize#1065]
Hi! I'm currently using Composer Normalize on a library created specifically for inclusion in Drupal core (https://github.com/php-tuf/composer-stager), where we have [a policy of evaluating the security policies of packages](https://www.drupal.org/about/core/policies/core-dependency-policies/dependency-info#criteria) before adding them as dependencies. I don't see any such policy here (e.g., at https://github.com/ergebnis/composer-normalize/security). Do you have one? If so, would you be kind enough to publish it? If not, would you consider creating one? Thank you!

**Comment by fredden** [comment]
Looking at https://github.com/php-tuf/composer-stager/blob/v1.2.1/composer.json#L19-L23, this package isn't in the dependency tree for the package you're looking at possibly including in Drupal core. The packages listed in `require-dev` will only be installed if you are installing that package on its own, not as a dependency of another package. See the "root-only" label here:
https://getcomposer.org/doc/04-schema.md#require-dev
https://getcomposer.org/doc/04-schema.md#root-package

**Comment by TravisCarden** [comment]
You are obviously correct, @fredden. Drupal implementers and end users will not get Composer Normalize in their codebases at all--even for local development. Composer Stager contributors, however, _will_ get it installed for local dev. And since Composer Stager is actually owned by the Drupal Association (a fact I see I failed to mention above), it comes under Drupal governance and is subject to all the same standards and policies. A security vulnerability affecting local development may be much less likely and arguably less of a risk, so a security policy in this case may therefore be something of a formality. It would just be convenient to have in case the Drupal security team looks for it. I certainly won't make a fuss if none is added.

**Comment by localheinz** [comment]
@TravisCarden 

Thank you for opening this issue, I will look into it!
