### ISSUE TITLE
Make versions separator customizable

### ISSUE THREAD

**Issue by vjik** [localheinz/composer-normalize#1107]
Now version always normalized to `^1.0 || ^2.0`.
I want use alternative separator: `^1.0|^2.0`.

Will be great add command argument that allow select strategy of version normalization:

• without normalization
• normalize to `^1.0|^2.0`
• normalize to `^1.0 || ^2.0`

**Comment by localheinz** [comment]
@vjik 

But why?

If you navigate to https://getcomposer.org/doc/articles/versions.md#version-range, you can see that the examples use ` || ` as version constraint separators. While `composer` supports using `|` as version constraint separators, I am reluctant to invest in another configuration option.

**Comment by vjik** [comment]
We discussed it with the team and decided switch to ` || `. 

But having a command argument for separator customization would still be cool 😎
