### ISSUE TITLE
Do not normalize x.y.*

### ISSUE THREAD

**Issue by jawira** [localheinz/composer-normalize#1156]
### Steps required to reproduce the problem

1. You must have a dependency version like "`6.3.*`"
2. Execute "composer normalize"

#### Expected Result

- Version should remain "`6.3.*`"

#### Actual Result

- Version is replaced by "`~6.3.0`"

***

I know the semantics of  "`6.3.*`" and  "`~6.3.0`" are the same, however in Symfony projects it is expected to use the "`*`" star symbol.

This is because it's part of their update procedure: https://symfony.com/doc/current/setup/upgrade_minor.html#1-update-the-symfony-library-via-composer

![image](https://github.com/ergebnis/composer-normalize/assets/496541/1da7d90c-bb04-4467-8a9b-08160c109b93)

As you can see the current Symfony's version is declared in "extra" section, which of course it's not modified by "normalize" command:

![image](https://github.com/ergebnis/composer-normalize/assets/496541/8147e9b3-5f83-4855-b481-5ad2d6144c65)

Can you revert this behavior? or maybe put an option for symfony users ? Thanks in advance

**Comment by fredden** [comment]
This change was introduced in https://github.com/ergebnis/json-normalizer/pull/756. Some discussion took place there regarding this specific change.

Would you like this tool to normalise the version constraint in `extra.symfony.require`? That way there would be consistency between the version constraints in the `require` section and this Symfony-specific field.

Or, are you asking for this tool to match the documentation provided by Symfony? In that case, I wonder if they would accept an update instead.

Or, perhaps you just prefer the wildcard and want to keep using that. In this case, you are requesting a configuration option to allow use of the wildcard range operator. (And this isn't anything to do with Symfony after all.) (Or that tilde operators are normalised to wildcards where possible.)

**Comment by jawira** [comment]
First, thank you for answering so quickly.

**IMHO** a tool must adapt to user's needs, so I think is better to keep the wildcard. Symfony is a pretty popular framework, I'm sure I will not be the only one to point out this behavior.

Now, how to achieve this ? maybe you could add a "level" option, _a la_ PHPStan <https://phpstan.org/user-guide/rule-levels>:

* So level1 will order composer.json keys. 
* Level2 will fix operators (from | to ||). 
* Level3 will refactor versions (from x.y.* to ~x.y.0)

Another possible solution is to add a profile options: `--profile=symfony` with all custom rules for a symfony project.

And for impatient people, they can fix `ergebnis/composer-normalize` version to `2.30`.

**Comment by localheinz** [comment]
@jawira 

> I know the semantics of "6.3.*" and "~6.3.0" are the same, however in Symfony projects it is expected to use the "*" star symbol.
>
>This is because it's part of their update procedure: https://symfony.com/doc/current/setup/upgrade_minor.html#1-update-the-symfony-library-via-composer

I do not see any problem here:

- you do not need to use a configuration for `/extra/symfony/require` in `composer.json`
- you do not need to use `5.4.*` as value for `/extra/symfony/require`, but could instead also use `~5.4.0` and everything works the same
- you do not need to use `ergebnis/composer-normalize`

I use `ergebnis/composer-normalize` in Symfony projects, too, and I do not use the wildcard version constraint. Everything works as expected.

**Comment by jawira** [comment]
@localheinz 

> I use ergebnis/composer-normalize in Symfony projects, too, and I do not use the wildcard version constraint. Everything works as expected.

I know it will work. It's not a technical problem, but a human one. At my workplace for example, my colleagues and future developers won't understand why the composer.json file doesn't follow the Symfony's documentation.

You can leave the issue closed, I will stay with `v2.30`.

Thank you for creating _composer normalize_ :) 👍
