### ISSUE TITLE
Readd PHP 7.4/8.0 support

### ISSUE THREAD

**Issue by mvorisek** [localheinz/composer-normalize#1236]
Simillar to https://github.com/ergebnis/phpunit-slow-test-detector/issues/369. This repo is development tooling and it should not limit other deps.

market share: https://stitcher.io/blog/php-version-stats-january-2023

In general, I would be happy if the php version policy can be adjusted to +5 years after the given php minor version "active support" [1] has ended. This is about the typical support time in major LTS linux distros [2], [3].

[1] https://www.php.net/supported-versions.php
[2] for ex. Debian has 5 years LTS support - https://wiki.debian.org/LTS
[3]  https://www.zend.com/blog/planning-php-7-4-eol

**Comment by localheinz** [comment]
@mvorisek 

I'm not sure if you are aware of it, but I maintain all of the packages in the @ergebnis organization myself. I currently have $114.00 in GitHub Sponsors a month. In November 2023, I spent 33.75 hours maintaining and contributing to open-source projects.

I would be happy to spend more time if I had more sponsors, but currently I see no value in spending even more time for the same amount of money with no added benefit.

![CleanShot 2023-12-11 at 09 05 31@2x](https://github.com/ergebnis/composer-normalize/assets/605483/87f96a3d-7c2b-4946-88eb-445d10c0c451)
