### ISSUE TITLE
Normalizes `"php": "^8.2 || ^8.3"` to `"php": "^8.2"` (not desirable)

### ISSUE THREAD

**Issue by simPod** [localheinz/composer-normalize#1293]
#### Steps required to reproduce the problem

```json
    "require": {
        "php": "^8.2 || ^8.3",
```

(I have lockfile)

#### Expected Result

Keep. I want to allow installing on both php versions.

#### Actual Result

Changes to 

```json
    "require": {
        "php": "^8.2",
```

**Comment by localheinz** [comment]
Duplicate of #1287.

**Comment by simPod** [comment]
Oh right. I'll go with `"~8.2.0 || ~8.3.0"`. Thanks!
