### ISSUE TITLE
Does not support complex version constraint rules

### ISSUE THREAD

**Issue by huangdijia** [localheinz/composer-normalize#1371]
#### Steps required to reproduce the problem

1. `composer r "friendsofphp/php-cs-fixer:~3.62.0, \!=3.63.0" --dev `
2. `composer normalize --dry-run --no-update-lock -vvv`

#### Result

```diff

./composer.json is not normalized.

---------- begin diff ----------
--- original
+++ normalized
@@ -43,7 +43,7 @@
         "elasticsearch/elasticsearch": "^7.0 || ^8.0",
         "ergebnis/composer-normalize": "^2.43",
         "friendsofhyperf/rector": "dev-main",
-        "friendsofphp/php-cs-fixer": "~3.62.0, !=3.63.0",
+        "friendsofphp/php-cs-fixer": "~3.62.0 !=3.63.0",
         "hashids/hashids": "^4.1 || ^5.0",
         "huangdijia/php-coding-standard": "^2.0",
         "hyperf/amqp": "~3.1.0",

----------- end diff -----------

```

**Comment by fredden** [comment]
https://getcomposer.org/doc/articles/versions.md#version-range

> You can define multiple ranges. Ranges separated by a space (` `) or comma (`,`) will be treated as a **logical AND**.

This tool is removing the two sequential separator characters that you have used (`,` followed by ` `) and replacing it with a single separator (` `).
