### ISSUE TITLE
New `allow-plugins` failed on GitHub actions

### ISSUE THREAD

**Issue by afbora** [localheinz/composer-normalize#832]
#### Steps required to reproduce the problem

GitHub action failed when new `allow-plugins` feature used.

composer.json

````json
"config": {
  "optimize-autoloader": true,
  "platform-check": false,
  "allow-plugins": {
    "getkirby/composer-installer": true
  }
},
````

> Running ergebnis/composer-normalize 2.18.0 by Andreas Möller and contributors.
> ./composer.json is not normalized.

Related GitHub Action:
https://github.com/getkirby/kirby/runs/4607152066?check_suite_focus=true

Related articles:
https://blog.packagist.com/composer-2-2/

https://getcomposer.org/doc/06-config.md#allow-plugins

**Comment by localheinz** [comment]
@afbora 

From what I can see in https://github.com/getkirby/kirby/runs/4607152066?check_suite_focus=true, it looks like `ergebnis/composer-normalize` works fine. The issue I can see there is that after the update of `ergebnis/composer-normalize`, your `composer.json` is not normalized anymore (see https://github.com/ergebnis/composer-normalize/issues/779).

Can you take a look at https://github.com/getkirby/kirby/pull/4067?

Perhaps it's best not to update all dependencies at once, what do you think?

**Comment by afbora** [comment]
Fixed with version update and `composer normalize`. Thank you.
